/*Write a multithreaded program that generates the Fibonacci series. This program should work as follows: 

The user will enter on the command line the number of Fibonacci numbers that the program is to generate. 
The program will then create a separate thread that will generate the Fibonacci numbers. 
When the thread finishes execution, the parent thread will output the sequence generated by the child thread. 
Because the parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, 
this will require having the parent thread wait for the child thread to finish.*/

#include <pthread.h>
#include <stdio.h>
int value = 0;
void *runner(void *param); /* the thread */
int main(int argc, char * argv[])
{
int pid;
pthread_t tid;
pthread_attr_t attr;
  pid = fork();
  
  if (pid == 0) {/* child process */
     pthread_attr_init(&attr);
     pthread_create(&tid,&attr,runner,NULL);
     pthread_join(tid,NULL);
     printf(“CHILD: value = %d”, value); /* LINE C */
  }
  else if (pid > 0) { /* parent provess */
     wait(NULL);
     printf(“PARENT: value = %d”, value); /* LINE P */
  }
}

void *runner(void *param) {
  value = 5;
  pthread_exit(0);
}
